version: '3.7'

services:
  arangodb:
    image: arangodb:latest
    restart: always
    environment:
      ARANGO_ROOT_PASSWORD: Appsmith
    ports:
      - "8529:8529"
    volumes:
      - ./seed.js:/docker-entrypoint-initdb.d/seed.js
