version: '3'
services:
  mail:
    image: bytemark/smtp
    restart: always
    ports:
     - "25:25"
    environment:
      RELAY_HOST: smtp.gmail.com
      RELAY_PORT: 587
      RELAY_USERNAME: appsmith
      RELAY_PASSWORD: appsmith