version: "3.9"
services:
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: MySecurePassword123!
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/seed.sql

